export const SET_LOCALIZATION = "SET_LOCALIZATION";
export const SET_GAME_STATE = "SET_GAME_STATE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_LOBBY = "UPDATE_LOBBY";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const SHOW_MODAL = "SHOW_MODAL";

export const GAME_STATE_MAIN_MENU = 0;
export const GAME_STATE_LOBBY_SEARCH = 1;
export const GAME_STATE_LOBBY = 2;
export const GAME_STATE_MISSION = 3;

export const MODAL_GENERIC = "MODAL_GENERIC";
export const MODAL_MISSION_SELECTOR = "MODAL_MISSION_SELECTOR";
export const MODAL_MISSION_VIEWER = "MODAL_MISSION_VIEWER";